# Generated by Django 4.0.2 on 2022-03-03 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwinningsperday',
            name='day',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='winperday',
            name='day',
            field=models.DateField(verbose_name=datetime.datetime(2022, 3, 3, 13, 59, 8, 888540)),
        ),
        migrations.AddConstraint(
            model_name='userwinningsperday',
            constraint=models.UniqueConstraint(fields=('user', 'contest', 'day'), name='unique_user_contest_date'),
        ),
    ]
