# Generated by Django 4.0.1 on 2022-02-01 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_winperday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='winperday',
            name='day',
            field=models.DateField(verbose_name=datetime.datetime(2022, 2, 1, 17, 0, 28, 998350)),
        ),
    ]
