# Generated by Django 4.0.1 on 2022-02-01 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_contest_end_alter_contest_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='winperday',
            name='attempts',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='winperday',
            name='day',
            field=models.DateField(verbose_name=datetime.datetime(2022, 2, 1, 21, 35, 29, 670119)),
        ),
        migrations.AlterField(
            model_name='winperday',
            name='winnings',
            field=models.IntegerField(default=1),
        ),
    ]
