# Generated by Django 4.0.1 on 2022-02-01 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_winperday_attempts_alter_winperday_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winperday',
            name='day',
            field=models.DateField(verbose_name=datetime.datetime(2022, 2, 1, 22, 9, 7, 621217)),
        ),
        migrations.AlterField(
            model_name='winperday',
            name='winnings',
            field=models.IntegerField(default=0),
        ),
    ]
