# Generated by Django 4.0.1 on 2022-02-01 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_winperday_day_alter_winperday_winnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winperday',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='winperday',
            name='day',
            field=models.DateField(verbose_name=datetime.datetime(2022, 2, 1, 22, 9, 27, 46636)),
        ),
    ]
